name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build tree
      run: yarn build
    - name: Run tests
      run: echo yarn test
